name: Deploy Application to EKS

## not deploy during push temporarily
#on:
#  push:
#    branches:
#      - dev
#    paths:
#      - 'app/**' # Trigger when application code changes

on:
 workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER_NAME: mundose-cluster # From Terraform outputs or a secret

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Deploy with Kubectl (if using raw manifests)
        working-directory: ./eks
        run: |
          aws eks update-kubeconfig --region us-east-1 --name mundose-cluster
          kubectl apply -f ./deployment.yml
          kubectl apply -f ./service.yml
          # Update image tag in deployment.yaml if necessary:
          kubectl set image deployment/mundose-deployment mundose=${{ secrets.ECR_REGISTRY_URL }}/mundose:latest
          kubectl rollout restart deployment
          sleep 30
          echo 'get endpoint url'
          kubectl get pods -o wide
          kubectl get service mundose-service
          ################################
          ##monitoring##
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.9.0'

      - name: Deploy Prometheus and Grafana stack
        working-directory: ./eks
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm uninstall prometheus-stack
          helm install prometheus-stack prometheus-community/kube-prometheus-stack \
            --set grafana.sidecar.dashboards.enabled=true \
            --set grafana.sidecar.dashboards.label="grafana_dashboard" \
            --values ./prometheus-stack.yml
      - name: Deploy Grafana dashboard ConfigMap
        working-directory: ./eks
        run: |
          kubectl apply -f ./grafana-dashboard.yml
          sleep 30
          echo 'get endpoint url'
          #kubectl get prometheus-stack-grafana
          kubectl get deployments
          kubectl get services