name: Deploy Application to EKS

## not deploy during push temporarily
#on:
#  push:
#    branches:
#      - dev
#    paths:
#      - 'app/**' # Trigger when application code changes

on:
 workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER_NAME: mundose-cluster # From Terraform outputs or a secret

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Deploy with Kubectl (if using raw manifests)
        working-directory: ./eks
        run: |
          aws eks update-kubeconfig --region us-east-1 --name mundose-cluster
          kubectl apply -f ./deployment.yml
          kubectl apply -f ./service.yml
          # Update image tag in deployment.yaml if necessary:
          kubectl set image deployment/mundose-deployment mundose=${{ secrets.ECR_REGISTRY_URL }}/mundose:latest
          kubectl rollout restart deployment
          sleep 30
          echo 'get endpoint url'
          kubectl get pods -o wide
          kubectl get service mundose-service
          ##monitoring##
          kubectl apply -f prometheus.yml
          kubectl apply -f grafana.yml
          sleep 30
          echo 'get grafana url'
          kubectl get svc grafana -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}'
          kubectl get service grafana
